# Generated by Django 3.2.4 on 2021-06-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_table_one_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_two',
            name='date_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
